spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always # data.sql이 항상 실행되도록 설정
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  flyway:
    enabled: false
